project:
  type: website

website:
  title: "Beatriz Lima Silveira"
  navbar:
    left: 
      - icon: github
        href: https://github.com/beatriz-ls
      - icon: linkedin
        href: https://linkedin.com
    right:
      - text: Softwares
        href: index.qmd#softwares
      - text: Skill Sets
        href: index.qmd#skillsets
      - text: Work
        href: index.qmd#work
      - text: Projects
        href: projects.qmd
      - about.qmd
      - text: CV
        href: resume.qmd
format:
  html:
    theme: minty
    css: styles.css
editor: visual

