project:
  type: website

website:
  title: "Beatriz Lima Silveira"
  navbar:
    left: 
      - icon: github
        href: https://github.com/beatriz-ls
      - icon: linkedin
        href: https://linkedin.com
    right:
      - about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: resume.qmd
format:
  html:
    theme: minty
    css: styles.css

editor: visual

