project:
  type: website

website:
  title: "Beatriz Lima"
  #favicon: {{< fa lemon title="a lemon" >}}
  navbar:
    left: 
      - icon: github
        href: https://github.com/beatriz-ls
      - icon: linkedin
        href: https://www.linkedin.com/in/beatriz-lima-silveira/
      - icon: envelope
        href: mailto:beatrizlimasilveira@gmail.com
    right:
      - about.qmd
      - text: Portfolio
        href: portfolio.qmd
      - text: Blog
        href: blog.qmd 
      - text: CV
        href: assets/CV.pdf
  page-footer: 
    background: light
    left: Website build with [Quarto](https://quarto.org/){target=_blank}
    right: Copyright 2024, Beatriz Lima
format:
  html:
    theme: mystyles.scss
    mainfont: Courier Prime
editor: visual

